// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5QM7u467JYe55u4m-Tx8ugru9DrxfeYc',
    appId: '1:384582288929:web:cf9ca69ae4e010fe0b8560',
    messagingSenderId: '384582288929',
    projectId: 'aether-b72f5',
    authDomain: 'aether-b72f5.firebaseapp.com',
    storageBucket: 'aether-b72f5.firebasestorage.app',
    measurementId: 'G-2XRE1S6GC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdJLi8KSOUaqryj2YbvTBLLYF-7zBni-w',
    appId: '1:384582288929:android:6e2156e970cae5be0b8560',
    messagingSenderId: '384582288929',
    projectId: 'aether-b72f5',
    storageBucket: 'aether-b72f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyd31gdjV-DAZu1eG_5O03z4nfMMNB8E',
    appId: '1:384582288929:ios:410291f6821aec090b8560',
    messagingSenderId: '384582288929',
    projectId: 'aether-b72f5',
    storageBucket: 'aether-b72f5.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOyd31gdjV-DAZu1eG_5O03z4nfMMNB8E',
    appId: '1:384582288929:ios:410291f6821aec090b8560',
    messagingSenderId: '384582288929',
    projectId: 'aether-b72f5',
    storageBucket: 'aether-b72f5.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5QM7u467JYe55u4m-Tx8ugru9DrxfeYc',
    appId: '1:384582288929:web:78a139d6035fe8ef0b8560',
    messagingSenderId: '384582288929',
    projectId: 'aether-b72f5',
    authDomain: 'aether-b72f5.firebaseapp.com',
    storageBucket: 'aether-b72f5.firebasestorage.app',
    measurementId: 'G-NB9VWJ05Y3',
  );

}